### ISSUE TITLE
planner should fail sometimes

### ISSUE THREAD

**Issue by thescouser89** [juanignaciosl/wedding-tables-planner-web#1]
![wedding_planner](https://cloud.githubusercontent.com/assets/630746/3118738/33576284-e73f-11e3-867b-6922f8a5b203.png)

Hi,

Really cool application! I'll definitely use it if one day I get married :grinning: 

So in the screenshot I tried to create an impossible planning where 3 persons want to sit in the same table, but the table can only accomodate 2 guests.

I'd expect the planner to just admit defeat and say I should cancel my wedding because I cannot accomodate all the guests' desires.

**Comment by juanignaciosl** [comment]
That's the first task in my TODO list ;-). OptaPlanner is as nice as it can be, and generate a "less-bad" solution. Under the hood this kind of arrangement gets a negative hard score. I'll warn user ASAP.

Stay tuned!

**Comment by juanignaciosl** [comment]
Should be solved now

**Comment by thescouser89** [comment]
Nice! Now I can start planning my wedding, while waiting for the right girl to appear! :laughing: 

Thanks for fixing it so fast! I'll try to use your project to figure out how to use OptaPlanner one day! :)
